// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6PPDOTPeHKBlg5Yy5pGEEWo3mCx2hGek',
    appId: '1:550613725736:web:abf2acab9a5cd634e43b1d',
    messagingSenderId: '550613725736',
    projectId: 'riverpod-firestore-strea-402e4',
    authDomain: 'riverpod-firestore-strea-402e4.firebaseapp.com',
    storageBucket: 'riverpod-firestore-strea-402e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOlwErxOLiS5OcsNds3kARe-WbNdTebE4',
    appId: '1:550613725736:android:028abbaddcf13a48e43b1d',
    messagingSenderId: '550613725736',
    projectId: 'riverpod-firestore-strea-402e4',
    storageBucket: 'riverpod-firestore-strea-402e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp0CL-JJb1FDb5GmlBhCV_PkGd5nkwAzE',
    appId: '1:550613725736:ios:f4743092aebcf7b8e43b1d',
    messagingSenderId: '550613725736',
    projectId: 'riverpod-firestore-strea-402e4',
    storageBucket: 'riverpod-firestore-strea-402e4.appspot.com',
    iosClientId: '550613725736-6emljk5lu5cjveicg8jumaape5op6p0b.apps.googleusercontent.com',
    iosBundleId: 'shop.hyeonseong.riverpodFirestoreStream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp0CL-JJb1FDb5GmlBhCV_PkGd5nkwAzE',
    appId: '1:550613725736:ios:f4743092aebcf7b8e43b1d',
    messagingSenderId: '550613725736',
    projectId: 'riverpod-firestore-strea-402e4',
    storageBucket: 'riverpod-firestore-strea-402e4.appspot.com',
    iosClientId: '550613725736-6emljk5lu5cjveicg8jumaape5op6p0b.apps.googleusercontent.com',
    iosBundleId: 'shop.hyeonseong.riverpodFirestoreStream',
  );
}
